version: '3.1'

services:
  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql/:/var/lib/postgresql
