version: '3.1'

services:
  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_HOST=${DB_POSTGRESDB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql/:/var/lib/postgresql
